# Generated by Django 4.0.2 on 2022-02-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=264)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
