# Generated by Django 4.0.2 on 2022-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhis',
            name='keyword',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
